# basic options
title: jamaki.io
author: James Maki
email: mail@jamaki.io
description: My personal site
twitter_username: jamaki_io
github_username:  jamaki-ibmi

# Build settings
markdown: kramdown
theme: minima
